### ISSUE TITLE
Utilise fallback handler when connecting to a server in maintenance mode

### ISSUE THREAD

**Issue by ClydeNoIQ** [pinkuth/Maintenance#2]
If the proxy server has a reconnection handler, people should be sent into other server instead of getting kicked also make it so you receive a message when trying to join the downstream server that is under maintenance instead of being kicked with the message.

Hope you like my idea :D

**Comment by ClydeNoIQ** [comment]
Also, please make a separate permission for maintenance access

**Comment by pinkuth** [comment]
> Also, please make a separate permission for maintenance access

Heya, please could you clarify what you mean by this? Are you meaning two sperate permissions for the maintenance command and joining during maintenance i.e:

- `maintenance.change` (for command)
- `maintenance.join` (for joining during maintenance)

Or are you implying something else?

**Comment by ClydeNoIQ** [comment]
> > Also, please make a separate permission for maintenance access
> 
> Heya, please could you clarify what you mean by this? Are you meaning two sperate permissions for the maintenance command and joining during maintenance i.e:
> 
> * `maintenance.change` (for command)
> * `maintenance.join` (for joining during maintenance)
> 
> Or are you implying something else?

Yep! It would be helpful since my staff members in my server keeps touching the maintenance command but I wanted to only give them permission to join

**Comment by ClydeplayzYT590** [comment]
If you don't mind, could you please make a jar file and make a new release? :D
